# Generated by Django 6.0.7 on 2026-08-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classteacher_deleted_at_classteacher_is_deleted'),
        ('schools', '0002_school_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school'),
            preserve_default=False,
        ),
    ]
