# Generated by Django 6.0.7 on 2026-08-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='school',
        ),
    ]
