# Generated by Django 6.0.7 on 2026-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_session_sessionreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='late_reference_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='teacher_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='total_late_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
