# Generated by Django 6.0.7 on 2026-08-24 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_session_sessionreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sessions_60', models.PositiveIntegerField(default=0)),
                ('sessions_90', models.PositiveIntegerField(default=0)),
                ('sessions_120', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'year', 'month'), name='unique_teacher_payroll_month')],
            },
        ),
        migrations.CreateModel(
            name='TeacherTermRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_rates', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rates', to='education.term')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'term'), name='unique_teacher_term_rate')],
            },
        ),
    ]
